services:
  classifier:
    build: .
    image: sinceai-classifier
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount a local directory for audio files
      - ./samples:/app/samples
      - ./docker_output:/app/output

  datagenerator:
    build:
      context: .
      dockerfile: Dockerfile.datagenerator
    image: sinceai-datagenerator
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./signals:/app/signals
      - ./backgrounds:/app/backgrounds
      - ./docker_dataset:/app/dataset

  trainclassifier:
    build:
      context: .
      dockerfile: Dockerfile.trainclassifier
    image: sinceai-trainclassifier
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./docker_dataset:/app/dataset
      - ./docker_output:/app/output
